# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        wid = 800
        hei = 800
        hei_row = 40
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(wid+10, hei)

        # MainWindow.showMaximized()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, wid//2 - 10, hei-hei_row*2))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutWidget.setStyleSheet("background-image: url('kitty.jpeg');")
        self.horizontalLayout_left = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_left.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_left.setObjectName("horizontalLayout_left")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(wid//2, hei_row*14+5, wid//2, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_right = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_right.setObjectName("horizontalLayout_right")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_left.addWidget(self.tableView)

        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setEnabled(True)
        self.label_1.setGeometry(QtCore.QRect(wid//2, 0, wid//2, hei_row))

        '''
        self.label_1.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
            "")
        '''
        self.label_1.setObjectName("label_1")
        self.label_1.setStyleSheet("background-color: rgb(255, 189, 205);")
        # self.horizontalLayout_right.addWidget(self.label_1)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(wid//2, hei_row, wid//2, hei_row))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(wid//2, hei_row*2, wid//2, hei_row*2))
        '''
        self.label_2.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
            "")
        '''
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("background-color: rgb(255, 189, 205);")

        '''

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(wid//2, hei_row*4, wid//2, hei_row))
        self.radioButton.setObjectName("radioButton")
        '''

        self.checkBox_lagrange = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_lagrange.setGeometry(QtCore.QRect(wid//2, hei_row*4, wid//2, hei_row))
        self.checkBox_lagrange.setObjectName("checkBox_lagrange")
        self.checkBox_newton = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_newton.setGeometry(QtCore.QRect(wid//2, hei_row*5, wid//2, hei_row))
        self.checkBox_newton.setObjectName("checkBox_newton")
        self.checkBox_lsm = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_lsm.setGeometry(QtCore.QRect(wid//2, hei_row*6, wid//2, hei_row))
        self.checkBox_lsm.setObjectName("checkBox_lsm")
        self.checkBox_linear_spline = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_linear_spline.setGeometry(QtCore.QRect(wid//2, hei_row*7, wid//2, hei_row))
        self.checkBox_linear_spline.setObjectName("checkBox_linear_spline")
        self.checkBox_quadratic_spline = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_quadratic_spline.setGeometry(QtCore.QRect(wid//2, hei_row*8, wid//2, hei_row))
        self.checkBox_quadratic_spline.setObjectName("checkBox_quadratic_spline")
        self.checkBox_cubic_spline = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_cubic_spline.setGeometry(QtCore.QRect(wid // 2, hei_row * 9, wid // 2, hei_row))
        self.checkBox_cubic_spline.setObjectName("checkBox_cubic_spline")
        self.checkBox_cubic_spline_BC = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_cubic_spline_BC.setGeometry(QtCore.QRect(wid // 2, hei_row * 10, wid // 2, hei_row))
        self.checkBox_cubic_spline_BC.setObjectName("checkBox_cubic_spline_BC")

        self.filter_button = QtWidgets.QPushButton(self.centralwidget)
        self.filter_button.setGeometry(QtCore.QRect(wid//2, hei_row*11, wid//2, hei_row))
        self.filter_button.setObjectName("filter_button")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(wid // 2, hei_row * 13, wid // 2, hei_row))
        '''
        self.label_2.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
            "")
        '''
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("background-color: rgb(255, 189, 205);")

        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setGeometry(QtCore.QRect(0, hei_row*6, wid//2, hei_row))
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        for _ in range(3):
            self.comboBox.addItem("")
        # self.comboBox.setStyleSheet("selection-background-color: rgb(255, 111, 149);")

        self.lineEdit_for_dot = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_for_dot.setGeometry(QtCore.QRect(wid // 2, hei_row*15, wid // 4-5, hei_row))
        self.lineEdit_for_dot.setObjectName("lineEdit_for_dot")
        # self.lineEdit_for_dot.setStyleSheet("background-color: rgb(255, 202, 219);")

        self.label_for_dot = QtWidgets.QLabel(self.centralwidget)
        self.label_for_dot.setGeometry(QtCore.QRect(wid // 4*3+5, hei_row * 15, wid // 4-5, hei_row))
        self.label_for_dot.setObjectName("label_for_dot")
        self.label_for_dot.setStyleSheet("background-color: rgb(255, 189, 205);")

        self.filter_button2 = QtWidgets.QPushButton(self.centralwidget)
        self.filter_button2.setGeometry(QtCore.QRect(wid // 2, hei_row * 16 + 5, wid // 2, hei_row))
        self.filter_button2.setObjectName("filter_button2")

        self.button_plus_row = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus_row.setGeometry(QtCore.QRect(0, hei-hei_row*2+5, wid // 8, hei_row))
        self.button_plus_row.setObjectName("button_plus_row")

        self.button_minus_row = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus_row.setGeometry(QtCore.QRect(wid // 8+5, hei - hei_row * 2 + 5, wid // 8, hei_row))
        self.button_minus_row.setObjectName("button_minus_row")

        self.horizontalLayout_right.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        app_icon = QtGui.QIcon("smile.png")
        MainWindow.setWindowIcon(app_icon)
        MainWindow.setWindowTitle(_translate("MainWindow", "окошко :.("))
        self.comboBox.setItemText(0, _translate("MainWindow", "  полиномом Лагранжа"))
        self.comboBox.setItemText(1, _translate("MainWindow", "  полиномом Ньютона"))
        self.comboBox.setItemText(2, _translate("MainWindow", "  метод наименьших квадратов"))
        self.filter_button.setText(_translate("MainWindow", "  построить график 🎀"))
        self.filter_button2.setText(_translate("MainWindow", "узнать результат 🎀"))
        self.button_plus_row.setText(_translate("MainWindow", "+рядочек"))
        self.button_minus_row.setText(_translate("MainWindow", "-рядочек"))
        self.lineEdit.setText(_translate("MainWindow", "табличк?.."))
        # self.lineEdit_for_dot.setText(_translate("MainWindow", "в какой точке смотрим??"))
        self.label_1.setText(_translate("MainWindow", "  можн выбрать другую табличку.."))
        self.label_2.setText(_translate("MainWindow", "  можн попытаться интерполир табл фукнцию..\n"
                                                      "  а если ничего не выбрать то ничего и не \n  проинтерполируется.."))
        '''
        self.label_2.setText(_translate("MainWindow", "можешь выбрать себе любую интерполяцию которую \nзахочешь\n"
                                                      "не розовую\n"
                                                      "ну не знаю.. что тебе нравится"))
        '''
        self.label_3.setText(_translate("MainWindow", "  а можн посмотреть значение в конкр точке!!"))
        self.label_for_dot.setText(_translate("MainWindow", "  тут будет у"))
        # self.radioButton.setText(_translate("MainWindow", "стираем предыдущий график"))
        self.checkBox_lagrange.setText(_translate("MainWindow", "  полиномом Лагранжа"))
        self.checkBox_newton.setText(_translate("MainWindow", "  полиномом Ньютона"))
        self.checkBox_lsm.setText(_translate("MainWindow", "  метод наименьших квадратов"))
        self.checkBox_linear_spline.setText(_translate("MainWindow", "  линейный сплайн"))
        self.checkBox_quadratic_spline.setText(_translate("MainWindow", "  квадратичный сплайн или как его"))
        self.checkBox_cubic_spline.setText(_translate("MainWindow", "  кубический сплайн ненатуральный"))
        self.checkBox_cubic_spline_BC.setText(_translate("MainWindow", "  кубический сплайн натуральный"))

    @QtCore.pyqtSlot()
    def changeSkinPink(self):
        pinkpalette = QtGui.QPalette()
        pinkpalette.setColor(QtGui.QPalette.Window, QtGui.QColor(255, 240, 250))
        pinkpalette.setColor(QtGui.QPalette.WindowText, QtGui.QColor(74, 0, 26))
        pinkpalette.setColor(QtGui.QPalette.Base, QtGui.QColor(255, 255, 255))
        pinkpalette.setColor(QtGui.QPalette.AlternateBase, QtGui.QColor(0, 0, 0))
        pinkpalette.setColor(QtGui.QPalette.ToolTipBase, QtGui.QColor(255, 158, 197))
        pinkpalette.setColor(QtGui.QPalette.ToolTipText, QtGui.QColor(74, 0, 26))
        pinkpalette.setColor(QtGui.QPalette.Text, QtGui.QColor(74, 0, 26))
        pinkpalette.setColor(QtGui.QPalette.Button, QtGui.QColor(255, 189, 205))
        pinkpalette.setColor(QtGui.QPalette.ButtonText, QtGui.QColor(74, 0, 26))
        pinkpalette.setColor(QtGui.QPalette.BrightText, QtGui.QColor(74, 0, 26))
        pinkpalette.setColor(QtGui.QPalette.Highlight, QtGui.QColor(255, 160, 173))
        pinkpalette.setColor(QtGui.QPalette.HighlightedText, QtGui.QColor(74, 0, 26))
        QtGui.QGuiApplication.setPalette(pinkpalette)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
